// DO NOT EDIT — generated by scripts/generate-swift-models.ts
// Source of truth: packages/shared/src/types/api-contracts.ts
// Regenerate: node scripts/generate-swift-models.ts

import Foundation

// MARK: - Device Management

/// POST /v1/devices/register — request body
struct DeviceRegisterRequest: Encodable, Sendable {
    let deviceId: String?
    let anonymousId: String
    let platform: String?
    let deviceModel: String?
    let osName: String?
    let osVersion: String?
    let appVersion: String?
    let buildNumber: String?
    let locale: String?
    let country: String?
    let timezone: String?

    enum CodingKeys: String, CodingKey {
        case platform, locale, country, timezone
        case deviceId = "device_id"
        case anonymousId = "anonymous_id"
        case deviceModel = "device_model"
        case osName = "os_name"
        case osVersion = "os_version"
        case appVersion = "app_version"
        case buildNumber = "build_number"
    }
}

/// POST /v1/devices/register — response
struct DeviceRegisterResponse: Decodable, Sendable {
    let deviceId: String
    let anonymousId: String
    let flagAssignments: [String: AnyCodable]
    let experimentAssignments: [String: AnyCodable]
    let config: DeviceConfig

    enum CodingKeys: String, CodingKey {
        case config
        case deviceId = "device_id"
        case anonymousId = "anonymous_id"
        case flagAssignments = "flag_assignments"
        case experimentAssignments = "experiment_assignments"
    }
}

struct DeviceConfig: Decodable, Sendable {
    let flushIntervalMs: Int
    let flushSize: Int

    enum CodingKeys: String, CodingKey {
        case flushIntervalMs = "flush_interval_ms"
        case flushSize = "flush_size"
    }
}

/// POST /v1/devices/:deviceId/identify — request body
struct DeviceIdentifyRequest: Encodable, Sendable {
    let userId: String
    let attributes: [String: AnyCodable]?

    enum CodingKeys: String, CodingKey {
        case attributes
        case userId = "user_id"
    }
}

/// POST /v1/devices/:deviceId/identify — response
struct DeviceIdentifyResponse: Decodable, Sendable {
    let deviceId: String
    let userId: String
    let anonymousId: String
    let mergeId: String?
    let mergeStatus: String?
    let flagAssignments: [String: AnyCodable]
    let experimentAssignments: [String: AnyCodable]

    enum CodingKeys: String, CodingKey {
        case deviceId = "device_id"
        case userId = "user_id"
        case anonymousId = "anonymous_id"
        case mergeId = "merge_id"
        case mergeStatus = "merge_status"
        case flagAssignments = "flag_assignments"
        case experimentAssignments = "experiment_assignments"
    }
}

// MARK: - SDK Config

/// GET /v1/config — response
struct SDKConfigResponse: Decodable, Sendable {
    let configVersion: String
    let etag: String
    let flags: [String: AnyCodable]
    let experiments: [String: SDKExperimentAssignment]

    enum CodingKeys: String, CodingKey {
        case etag, flags, experiments
        case configVersion = "config_version"
    }
}

struct SDKExperimentAssignment: Decodable, Sendable {
    let variantKey: String
    let payload: [String: AnyCodable]

    enum CodingKeys: String, CodingKey {
        case payload
        case variantKey = "variant_key"
    }
}

// MARK: - Event Ingestion

/// POST /v1/ingest — request body
struct IngestRequest: Encodable, Sendable {
    let batch: [IngestEvent]
    let context: IngestContext?
    let sentAt: String

    enum CodingKeys: String, CodingKey {
        case batch, context
        case sentAt = "sent_at"
    }
}

struct IngestEvent: Encodable, Sendable {
    let type: String // "track"
    let event: String
    let properties: [String: AnyCodable]?
    let timestamp: String?
}

struct IngestContext: Encodable, Sendable {
    let app: IngestApp?
    let user: IngestUser?
    let device: IngestDevice?
    let session: IngestSession?
    let flags: [String: AnyCodable]?
    let experiments: [String: AnyCodable]?
    let account: IngestAccount?
    let revenue: IngestRevenue?
    let releaseId: String?

    enum CodingKeys: String, CodingKey {
        case app, user, device, session, flags, experiments, account, revenue
        case releaseId = "release_id"
    }
}

struct IngestApp: Encodable, Sendable {
    let version: String?
    let build: String?
    let namespace: String?
}

struct IngestUser: Encodable, Sendable {
    let id: String?
    let anonymousId: String?

    enum CodingKeys: String, CodingKey {
        case id
        case anonymousId = "anonymous_id"
    }
}

struct IngestDevice: Encodable, Sendable {
    let id: String?
    let platform: String?
    let model: String?
    let osVersion: String?
    let locale: String?
    let country: String?

    enum CodingKeys: String, CodingKey {
        case id, platform, model, locale, country
        case osVersion = "os_version"
    }
}

struct IngestSession: Encodable, Sendable {
    let id: String?
}

struct IngestAccount: Encodable, Sendable {
    let id: String?
    let plan: String?
    let segment: String?
}

struct IngestRevenue: Encodable, Sendable {
    let amount: Double?
    let currency: String?
}

/// POST /v1/ingest — response (202)
struct IngestResponse: Decodable, Sendable {
    let accepted: Int
    let rejected: [IngestRejection]?
    let validationWarnings: [IngestWarning]?

    enum CodingKeys: String, CodingKey {
        case accepted, rejected
        case validationWarnings = "validation_warnings"
    }
}

struct IngestRejection: Decodable, Sendable {
    let index: Int
    let event: String
    let reason: String
}

struct IngestWarning: Decodable, Sendable {
    let index: Int
    let event: String
    let field: String
    let message: String
}

// MARK: - Flag Evaluation (server-side)

/// POST /v1/flags/evaluate — request body
struct EvaluateFlagsRequest: Encodable, Sendable {
    let flagKeys: [String]
    let context: [String: AnyCodable]

    enum CodingKeys: String, CodingKey {
        case context
        case flagKeys = "flag_keys"
    }
}

/// POST /v1/flags/evaluate — response
struct FlagEvaluationResult: Decodable, Sendable {
    let value: AnyCodable
    let reason: String
    let ruleId: String?

    enum CodingKeys: String, CodingKey {
        case value, reason
        case ruleId = "rule_id"
    }
}

// MARK: - Client-Side Config Types

/// Flag config for client-side evaluation (from GET /v1/config full mode)
struct FlagConfig: Codable, Sendable {
    let key: String
    let enabled: Bool
    let defaultValue: AnyCodable
    let flagType: String
    let rules: [FlagRule]

    enum CodingKeys: String, CodingKey {
        case key, enabled, rules
        case defaultValue = "default_value"
        case flagType = "flag_type"
    }
}

struct FlagRule: Codable, Sendable {
    let conditions: [FlagCondition]
    let value: AnyCodable
    let percentage: Int
    let enabled: Bool
}

struct FlagCondition: Codable, Sendable {
    let field: String
    let op: String // eq, neq, in, not_in, gt, gte, lt, lte, contains, exists
    let values: [AnyCodable]
}

/// Experiment config for client-side bucketing
struct ExperimentConfig: Codable, Sendable {
    let key: String
    let name: String
    let status: String // draft, running, paused, completed
    let trafficPct: Int
    let variants: [ExperimentVariant]

    enum CodingKeys: String, CodingKey {
        case key, name, status, variants
        case trafficPct = "traffic_pct"
    }
}

struct ExperimentVariant: Codable, Sendable {
    let key: String
    let name: String
    let weight: Int
    let isControl: Bool
    let payload: [String: AnyCodable]?

    enum CodingKeys: String, CodingKey {
        case key, name, weight, payload
        case isControl = "is_control"
    }
}

/// Full SDK config (for client-side evaluation mode)
struct SDKFullConfig: Codable, Sendable {
    let flags: [String: FlagConfig]
    let experiments: [String: ExperimentConfig]
    let serverTime: String

    enum CodingKeys: String, CodingKey {
        case flags, experiments
        case serverTime = "server_time"
    }
}

/// Public result of experiment assignment
public struct ExperimentResult: Sendable {
    public let variant: String
    public let payload: [String: AnyCodable]?
}

// MARK: - Shared Wrappers

struct ApiDataResponse<T: Decodable & Sendable>: Decodable, Sendable {
    let data: T
}

struct ApiErrorResponse: Decodable, Sendable {
    let error: ApiErrorDetail
}

struct ApiErrorDetail: Decodable, Sendable {
    let code: String
    let message: String
}
